swagger: "2.0.0"
info:
  title: Test API Documentation (Prodigal AI)
  description: Api Documentation for NFT Marketplace
  version: 1.0.0
  contact:
    email: choudharysidharth082000@gmail.com
  servers:
    - url: "http://localhost:3000"
      description: "Local Server Running"
    - url: "https://testcyberflow.herokuapp.com"
      description: "Main Server"

schemes: [http, https]

paths:
  /api/v1/test:
    get:
      tags:
        - name: Test API
      summary: Test Api
      description: Return HEllo world
      responses:
        200:
          description: OK    
          schema: 
            type: object
            properties:
              message:
                type: string     
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /api/v1/auth/signup:
    post:
      tags:
        - Auth
      summary : Signup User
      description: User Authentication which included login and signup
      parameters:
        - name: authBody
          in: body
          schema:
            type: object
            properties:
              name: 
                type: string
              emailUser:
                type: string
              password: 
                type: string
      responses:  
        200:
          description: SUCCESS 
  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary : Login User
      description: User Authentication which included login and signup
      parameters:
        - name: authBody
          in: body
          schema:
            type: object
            properties:
              emailUser: 
                type: string
              password:
                type: string
      responses:  
        200:
          description: SUCCESS 
           







